# docker stop <ID_DO_PGADMIN> <ID_DO_POSTGRES>
# docker rm <ID_DO_PGADMIN> <ID_DO_POSTGRES>
# docker-compose up -d

version: '3.8'

services:
  # Serviço do PostgreSQL
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=database_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Serviço do pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres_db
    
volumes:
  postgres_data: